services:
  satellite:
    build:
      context: images
      dockerfile: satellite.Dockerfile
    container_name: satellite
    expose:
      - 9000

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - satellite
    ports:
      - "80:80"
